# Generated by Django 5.0.3 on 2024-04-24 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_description_alter_event_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, default=1, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
    ]
