# Generated by Django 5.0.3 on 2024-05-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_creator_alter_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creator',
            new_name='UID',
        ),
    ]
