# Generated by Django 5.0.3 on 2024-05-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_creator_event_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='UID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
