# Generated by Django 5.0.3 on 2024-05-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='UID',
            new_name='uid',
        ),
    ]
